project:
  type: website
  output-dir: ../_site/es   # Guarda la salida dentro de _site/es/

website:
  title: "Gabriel Ramírez-Vilchis"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: research.qmd
        text: Investigación
      - href: publications.qmd
        text: Publicaciones
      - href: teaching.qmd
        text: Docencia
      - text: "Blog"
        menu:
          - href: blog/science.qmd
            text: "Ciencia y Código"
          - href: blog/books.qmd
            text: "Reseñas de Libros"
      - text: "Más"
        menu:
          - href: presentations.qmd
            text: "Presentaciones y Congresos"
          - href: training.qmd
            text: "Cursos y Capacitación"
          - href: awards.qmd
            text: "Premios y Reconocimientos"
          - href: memberships.qmd
            text: "Afiliaciones"
          - href: beyond.qmd
            text: "Más allá del Lab"
      - href: cv.qmd
        text: CV
    right:
      - icon: globe
        text: "Idioma"
        menu:
          - text: "English"
            href: /index.html
          - text: "Español"
            href: /es/index.html
      - icon: github
        href: https://github.com/tu-usuario
      - icon: linkedin
        href: https://linkedin.com/in/tu-usuario

format:
  html:
    theme:
      light: minty
      dark: slate
    css: ../styles.css
    toc: true