name: Publish Quarto Website

on:
  push:
    branches: [ master, main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      # 1. Compila la versión en inglés en _site/
      - name: Render English Site
        run: quarto render

      # 2. Compila la versión en español en _site/es/
      - name: Render Spanish Site
        run: |
          cd es
          quarto render

      # 3. Configura las páginas de GitHub
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # 4. Empaqueta el resultado compilado
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'

      # 5. Despliega el artefacto en GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4